version: 2.1
orbs:
  snyk: snyk/snyk@0.0.12
defaults: &defaults
  docker:
    - image: node:10.22
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: npm install
  test-snyk:
    <<: *defaults
    steps:
      - run: |
          apt-get update
          apt-get install sudo
      - snyk/scan:
            fail-on-issues: false

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-snyk:
          requires:
            - build
