version: 2.1
orbs:
  snyk: snyk/snyk@0.0.12
jobs:
  build:
    docker:
      - image: node:10.22
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: npm install
  snyk:
    steps:
      - run: |
          apt-get update
          apt-get install sudo
      - snyk/scan:
            fail-on-issues: false
